### ISSUE TITLE
Inventory Stock Status Page

### ISSUE THREAD

**Issue by acerapa** [acerapa/sims#93]
**TODOS:**
- [ ] Display the product by category
- [ ] Get the status of each products from, On hand, On Sale, Available, On PO
- [ ] Track if the product has pending order and incoming PO and for products with `reordering point` track when will be the next date to order.

Please refer to this image for ideas on how to implement the page.

![Image](https://github.com/user-attachments/assets/cd8e90b3-1d78-4410-a2dd-f62e2fec72c9)

**Comment by acerapa** [comment]
Merge layout for the Inventory Stock Status Page #99

**Comment by acerapa** [comment]
**Progress Update**

- updated products seeder status column values from ('inventory','non-inventory') to ('active', 'inactive')
- updated `inventoryStockStatus` api endpoint for products grouped by caegories
  - Get on_hand
  - Get  on_PO
- Added new relationship between `Product` and `ProductOrder`
- updated `ProductOrder` in column `status` to set default value to `OPEN`
- Added new end point test in `rest.http`

detailed changes here: https://github.com/acerapa/sims/pull/103
